# Generated by Django 2.0.1 on 2018-01-27 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'comment',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendsbook.Comment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'comment_like',
                'db_table': 'comment_like',
            },
        ),
        migrations.CreateModel(
            name='ConsistOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadmin', models.SmallIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'consist_of',
                'db_table': 'consist_of',
            },
        ),
        migrations.CreateModel(
            name='FriendsWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('confirm_request', models.SmallIntegerField(default=1)),
                ('blocked_status', models.IntegerField(default=0)),
                ('fusername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fusername', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FriendsWith',
                'db_table': 'friends_with',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('gname', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('privacy', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'group',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete='CASCADE', related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='chat/image')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fusername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fchat_username', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Message',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(blank=True, max_length=20, null=True)),
                ('emailid', models.CharField(max_length=30)),
                ('country_code', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=6)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Profile',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='updated status', max_length=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/image')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.CharField(blank=True, default='fs', max_length=5, null=True)),
                ('gid', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('likes', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Status',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='StatusLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendsbook.Status')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'StatusLikes',
                'db_table': 'status_likes',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='profileCover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profileCover', to='friendsbook.Status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='friendsbook.Status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groups',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_photo', to='friendsbook.Status'),
        ),
        migrations.AddField(
            model_name='groups',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='friendsbook.Status'),
        ),
        migrations.AddField(
            model_name='consistof',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupid', to='friendsbook.Groups'),
        ),
        migrations.AddField(
            model_name='consistof',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendsbook.Status'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
