# Generated by Django 2.0.2 on 2018-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileViews',
            field=models.IntegerField(default=0),
        ),
    ]
