# Generated by Django 2.0.2 on 2018-02-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consistof',
            name='gadmin',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(default='updated status', max_length=30, null=True),
        ),
    ]
