# Generated by Django 2.0.2 on 2018-02-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(default='updated status', max_length=30, null=True),
        ),
    ]
