# Generated by Django 2.0.2 on 2018-02-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0002_auto_20180214_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='sid',
        ),
        migrations.AlterField(
            model_name='consistof',
            name='gadmin',
            field=models.SmallIntegerField(default=0),
        ),
    ]
