# Generated by Django 2.0.2 on 2018-02-16 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0002_auto_20180214_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='sid',
        ),
        migrations.AlterField(
            model_name='consistof',
            name='gadmin',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groups',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='friendsbook.Status'),
        ),
    ]
