# Generated by Django 2.0.2 on 2018-04-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0004_auto_20180409_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
