# Generated by Django 2.0.2 on 2018-04-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0005_auto_20180410_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
