# Generated by Django 2.0.2 on 2018-02-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0005_auto_20180216_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='sid',
        ),
        migrations.AddField(
            model_name='groups',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='friendsbook.Status'),
        ),
    ]
