# Generated by Django 2.0.2 on 2018-02-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0006_auto_20180216_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupContainsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendsbook.Groups')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendsbook.Status')),
            ],
            options={
                'verbose_name_plural': 'GroupContainsStatus',
                'db_table': 'GroupContainsStatus',
            },
        ),
    ]
