# Generated by Django 2.0.2 on 2018-02-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0007_groupcontainsstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='gid',
        ),
    ]
