# Generated by Django 2.0.2 on 2018-04-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0007_remove_groups_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
