# Generated by Django 2.0.2 on 2018-02-17 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendsbook', '0008_remove_status_gid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consistof',
            unique_together={('gid', 'username')},
        ),
    ]
