# Generated by Django 2.0.2 on 2018-02-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0009_auto_20180217_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emailid',
            field=models.EmailField(max_length=30),
        ),
    ]
