# Generated by Django 2.0.2 on 2018-04-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0010_auto_20180411_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(default='updated status', max_length=15, null=True),
        ),
    ]
