# Generated by Django 2.0.2 on 2018-02-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0012_auto_20180221_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcontainsstatus',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='groupcontainsstatus',
            name='sid',
        ),
        migrations.DeleteModel(
            name='GroupContainsStatus',
        ),
    ]
