# Generated by Django 2.0.2 on 2018-02-22 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0013_auto_20180221_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='status',
            name='privacy',
            field=models.CharField(choices=[('fsofs', 'Friends Of Friends'), ('Pbc', 'Public'), ('fs', 'Friends')], default='fs', max_length=5, null=True),
        ),
    ]
