# Generated by Django 2.0.2 on 2018-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0019_auto_20180225_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_read',
            field=models.SmallIntegerField(default=0),
        ),
    ]
