# Generated by Django 2.0.2 on 2018-02-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0023_auto_20180225_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('P', 'Posted'), ('L', 'Liked'), ('C', 'Commented'), ('E', 'Edited Post'), ('S', 'Also Commented'), ('R', 'Send Request'), ('CN', 'Confirm Request')], max_length=2),
        ),
    ]
