# Generated by Django 2.0.2 on 2018-02-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0026_auto_20180225_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='gid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friendsbook.Groups'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('P', 'Posted'), ('L', 'Liked'), ('C', 'Commented'), ('E', 'Edited Post'), ('S', 'Also Commented'), ('SR', 'Send Request'), ('CR', 'Confirm Request'), ('PG', 'Posted in Group')], max_length=2),
        ),
    ]
