# Generated by Django 2.0.2 on 2018-03-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendsbook', '0027_auto_20180225_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friendsbook.Comment'),
        ),
    ]
