# Generated by Django 2.0.2 on 2018-04-01 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendsbook', '0029_auto_20180328_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=40)),
                ('course_class', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.CharField(blank=True, max_length=4, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'education',
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=40)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.CharField(blank=True, max_length=20, null=True)),
                ('WorkingFrom', models.CharField(blank=True, max_length=4, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'working',
                'db_table': 'working',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('P', 'Posted'), ('L', 'Liked'), ('C', 'Commented'), ('CL', 'Comment Like'), ('E', 'Edited Post'), ('S', 'Also Commented'), ('SR', 'Send Request'), ('CR', 'Confirm Request'), ('PG', 'Posted in Group')], max_length=2),
        ),
    ]
